registers/urls.py
from django.urls import path

from registers import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView

app_name ='register_app'

urlpatterns = [
    path('login/',views.loginPage,name="login"),
    path('register/',views.SignupView,name="register"),
    path('logout/',views.UserLogout.as_view(),name="logout"),
    # path('dash/<int:cid>/',views.dashboard_data,name = "dash-price-data")
  
    # path('logout/',a)
   
]



'''
for which email is sent use SMTP configuration in settings.py
https://docs.djangoproject.com/en/3.0/topics/auth/default/
Submit email form    -->PasswordResetViews.as_views()
email sent success  -->PasswordResetDoneView.as_views()
Link to password reser form in email ---user see email   -->PasswordResetConfirmView.as_views()
password sucessfully changed message and user can login using new password   -->PasswordResetCompleteView.as_views()


-------------------------------------------------------------
-->python decouple concept for email and other things secrete|
--------------------------------------------------------------
'''

sales/urls.py
from django.urls import path
from .views import *

urlpatterns=[
path('',sales_list,name='sales-list'),
path('customers/index/',manage_customers,name='customer-list'),
  path('<pk>/update/', CustomerUpdateView.as_view(), name='customer-update'),
path('<pk>/delete/', CustomerDeleteView.as_view(), name='customer-delete'),
path('create-customer/', CustomerAddView.as_view(), name='create-customer'),
path('sale-detail/<int:pk>',sales_details, name='sales_details'),
path('sales-detail/<int:pk>',sales_details_from_report, name='sales_details_from_report'),

path('<int:sales_id>/update/', SalesUpdateView, name='sales-update'),
path('return/',view_customer_return,name='sales-return-list'),
path('return/<pk>/',return_customer_each_sales,name='return-customer-sale'),
path('existing/',existing_customer_list,name='existing-customer-list'),
path('create/<int:pk>',SalesCreateView.as_view(),name='sales-create'),

path('exist/create/<int:pk>',existing_sales_create.as_view(),name='existing-sales-create'),
path('<int:pk>/return/',SalesReturnView.as_view(),name='sales-return'),

path('get-total-stock/',get_total_stock,name='get-total-stock'),
path('sales-item-total-price/',sales_item_total_price,name='sales-item-total-price'),
path('return-product-list/',product_return_list,name='return-product-list'),


]

school_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
urlpatterns = [
  path('dashboard/', dashboard, name='home'),
  path('', front_page, name='front_page'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    	path('authentication/',include('registers.urls', namespace = 'register_app')),
    # path('', include('corecode.urls')),
    # path('student/', include('students.urls')),
    # path('finance/', include('finance.urls')),
    path('inventory/', include('Inventory.urls')),
    path('supplier/', include('supplier.urls')),
    path('sales/', include('sales.urls')),
        path('report/', include('report.urls')),
    
	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		 name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		 name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		 name="password_reset_confirm"),  
	   
	 #<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	 #<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		 name="password_reset_complete"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

registers/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User#for profile i need User

from django.dispatch import receiver
from django.db.models.signals import post_save#user object  signal create hunxa




class Profile(models.Model):#THis is employee profile
	#in django username [assword1 and password2 are default field --but we make this model if we want to add extra field]
 
	user = models.OneToOneField(User, on_delete=models.CASCADE)#one user have one user nad pw so onetoone field
 
	fname = models.CharField(max_length=100,null=True)#null true means use value when needed
	lname = models.CharField(max_length=100,null=True)
	address = models.CharField(max_length=100, null=True)
	contact = models.CharField(max_length=100,null =True)
	email=models.EmailField(max_length=100,null=True)
	# profile_img = models.ImageField(null=True, blank=True)
 
	def __str__(self):
		return self.user.username    #i use this function because i dont use null =True in user -everytime i need this
	
	
	class Meta:
		verbose_name_plural ='Profile'
		db_table = 'tbl_profile'

		
		
	def save(self,*args,**kwargs):
		super().save(*args,**kwargs)
  
  

		
		
	
	
	@receiver(post_save, sender = User)#post save paxi uend by user--for register
	def update_profile(sender,instance,created,*args,**kwargs):
		if created:
			Profile.objects.create(user=instance)
			instance.profile.save()
			
			
			
			

registers/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,PasswordResetForm,AuthenticationForm

from django import forms
from django.forms import EmailField,TextInput,PasswordInput,ImageField







class LoginForm(AuthenticationForm):
	# email = EmailField(label=_("Email"), required=True,help_text=_("Required.")) #Email address is protected
	pass
	
	
	#although i write email field in models this field is compulsary for extra email authentication
	#if i want to add contact i can also add contact and other that should be in model
	
	#writing meta for this is optional
	
	# class Meta:
	#     model = User
	#     fields=('username','email','password')
		
   
	

class SignupForm(UserCreationForm):
	username=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Username",}))
	email=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Email",}))
	password1=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Enter Password",'type' : 'password'}))
	password2=forms.CharField(widget=forms.TextInput(attrs={"placeholder": " Confirm Password",'type' : 'password'}))
	

	class Meta:
		model = User
		

		fields = ('username','email','password1','password2',)#'__all__' also
	 
		#email fifeld is added later
		
		#help_text will remove the default text in signup page
		help_texts= {
			'username':None,
			# 'email':"Your email should contain @" if i add email and wants help_texts for that
		   #to remove help text of password and password2 go to UserCreationForm  and comment help_text in 
		}

registers/views.py
from django.shortcuts import render,reverse,redirect,resolve_url

# from django.http import HttpResponseRedirect
from django.contrib.auth.views import LoginView,LogoutView
from django.conf import settings
from django.views.generic import CreateView
from .forms import SignupForm,LoginForm
from django.contrib import messages
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from .decorators import unauthenticated_user, allowed_users, admin_only
from django.http import HttpResponse, HttpResponseRedirect
import json

from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
# from datetime import datetime
# from django.utils.timezone import datetime
from datetime import datetime, timedelta





def first_page(request):
	current_date = datetime.now()
	return render(request,'registers/firstpage.html',{'current_date':current_date})



#Login views
@unauthenticated_user
def loginPage(request):
	form = LoginForm()
	# form = LoginForm(reequest.POST or None)

	if request.method == 'POST':
		username = request.POST.get('username')
		password =request.POST.get('password')
		email =request.POST.get('email')
		user = authenticate(request,email=email, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.error(request, 'Username OR password is incorrect')

	context = {'form':form}
	return render(request, 'registers/login.html', context)



#Usersignup views
@unauthenticated_user
def SignupView(request):

	form = SignupForm()
 
	if request.method == 'POST':
		form = SignupForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')#retrieving username from save data from form

			group = Group.objects.get(name='employee')#any time a user signup it is associated with employee group directly
			user.groups.add(group)
			print("--------------",user)

			messages.success(request, 'Account was created for ' + username)

			return redirect('register_app:login')
		

	context = {'form':form}
	return render(request, 'registers/register.html', context)


#User logout views
class UserLogout(LogoutView):
	'''
	I use LOGOUT_REDIRECT_URL in setting.py so,when i logout then setting ma set garako url ma janxa for logout
	LOGOUT_REDIRECT_URL = '/user/login/
	'''
	# template_name = 'logout.html'
	pass







































# def employeeProfile(request):
#     return render(request,'registers/user_view.html')


# @admin_only
# def adminProfile(request):
#     return render(request,'registers/admin_view.html')


	
# # from django.contrib.auth.mixins import LoginRequiredMixin

# # @allowed_users(allowed_roles=['admin'])
# @login_required(login_url='/user/login/')
# @admin_only
# def dashboard(request):
# 	# customer = Customer.objects.get(pk=cid)
# 	customers=Customer.objects.all()
# 	total_customers=customers.count()
# 	orders=Order.objects.all()

# 	total_orders=orders.count()
# 	products = Product.objects.all()
# 	total_products = products.count()	
# 	pending=orders.filter(status='Pending').count()#filter la choose(search)  garxa and all pending lai count garxa
# 	delivered=orders.filter(status="Delivered").count()
 
 
# 	myFilter = CustomerFilter(request.GET, queryset=customers)
# 	customers = myFilter.qs #in jinja this customers goes

# 	# today_date = datetime.today()#filter every day order product for daily expenses	

# 	# today_customers = customers.filter(date_created__year = today_date.year,date_created__month = today_date.month,
#     #                                 date_created__day = today_date.day).count()
    
# 	today_customers = customers.filter(date_created__gte = datetime.now() - timedelta(days=1)).count()#details of last 24 hours#b4 i also get same output using above line but now not so use this concept
 
																									
	
# 	# today_order = orders.filter(created_at__year = today_date.year,created_at__month = today_date.month,created_at__day = today_date.day)
# 	today_order = orders.filter(created_at__gte = datetime.now() - timedelta(days=1))

# 	order_total_price=0.00
# 	for order in today_order:
# 		per_total_price = float(order.product.price) * order.quantity
		
# 		order_total_price += per_total_price
  
# 	print(order_total_price)
# 	# customer = Customer.objects.get(pk=cid) #but i need pk = cid(update)
# 	# particular_customer_price=0.00
# 	# for order in customer.order_set.all():
# 	# 	per_total_price = float(order.product.price) * order.quantity
# 	# 	particular_customer_price += per_total_price 
# 	context={
# 			'customers':customers,'orders_total_price':order_total_price,'total_orders':total_orders,
#    			'myFilter':myFilter,'today_customers':today_customers,'current_data':datetime.now(),
# 			'orders_pending':pending,'orders_delivered':delivered,'total_products':total_products,'total_customers':total_customers
# 			}
	
# 	return render(request,'registers/index.html',context)




	
	
	

registers/templates/registers/firstpage.html
{% extends 'base.html' %}

{% block title %}Home{% endblock%}

{% block javascript %}
{% endblock %}

{% block content %}


<body class="sb-nav-fixed">

   

<div class="row">
    <nav  class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Supermarket</a>
        <!-- <button class="btn btn-link btn-sm order-1 order-lg-0"
            id="sidebarToggle" href="#">
            <span class="navbar-toggler-icon"></span>
        </button> -->

        <button type="button" id="sidebarToggle" class="btn btn-warning text-black-50">
            <i class="fas fa-align-left"></i>
          </button>

         

           <!-- <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
          data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
          </button>
       
  
        <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->
   

        {% if request.user.is_authenticated  %}

        <div class="col">
       
                
            <a class="float-right" style="color:white;"> Hello, {{request.user.username}} </a>
           
        </div>

                {% if request.user.is_superuser %}


         
                
            <!-- <button  class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#adminModel">
                I am getting profile in the same page so dont need href i include user_view in this page

              <i class="fas fa-eye"></i>  Profile

            </button> -->


                <div class="col">
                    <a class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#logOutModal" style="cursor: pointer;">  <i class="fa fa-sign-in-alt"></i> LOGOUT</a>
                 </div>

                 {% else %} 

                 <!-- <button  class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#employeeModel">
                     I am getting profile in the same page so dont need href i include user_view in this page

                <i class="fas fa-eye"></i>  Profile

                 </button> -->
                 <div class="col">
                     <a class="btn btn-sm btn-warning float-right" data-toggle="modal" data-target="#logOutModal" style="cursor: pointer;">  <i class="fa fa-sign-in-alt"></i> LOGOUT</a>
                  </div>

                {% endif %}
                
         {% else %}

         <div class="col">
          
                
            <a class="float-right" style="color:white;"> Hello, Unknown </a>
           
        </div>

        <div class="col">
            <a href="{% url 'register_app:login'%}" class=" btn btn-sm btn-warning float-right" style="color:black;width:100px;">
                    
                <span><i class="fa fa-sign-in-alt"></i>  LOGIN</span>

            
             </a>

        </div>

           
     <a href="{% url 'register_app:register'%}" class=" btn btn-sm btn-warning" style="color:black;width:100px;">
        <span>

            <i class="fa fa-user-plus"></i>  SIGNUP
        </span>

    </a>
    

     {% endif %}

      
      
      
    </nav>

</div>

{% include 'registers/user_view.html' %}

{% include 'registers/admin_view.html' %}


<div id="logOutModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Want to leave ?</h4>
                <button class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                Press logout to leave !
            </div>
            <div class="modal-footer">
                <button class="btn btn-success" data-dismiss="modal"><!--model-dismiss la same page ma lauxa-->
                    Stay Here
                </button>
                <a class="btn btn-danger"  href="{% url 'register_app:logout' %}">
                    Logout</a>
            </div>
        </div>
    </div>
</div>

    <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Products</a>
            </li>
          </ul>
        </div>
      </nav> -->

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <!-- <div class="sb-sidenav-menu-heading">Functions</div> -->
                        {% if request.user.is_superuser %}
                        <a class="nav-link" href="/dashboard">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-tachometer-alt"></i>
                            </div>
                            Dashboard
                        </a>
                        {% endif %}
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                            aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-columns"></i>
                            </div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="(collapse)" id="collapseLayouts" aria-labelledby="headingOne"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'product_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Products</span></a>
                                <a class="nav-link" href="{% url 'order_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Orders</span></a>
                                <a class="nav-link" href="{% url 'customer_app:list'%}"><i class="fas fa-bars"></i><span class="ml-1">Customers</span></a>
                            </nav>
                        </div>
                        

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                            aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-book-open"></i>
                            </div>
                            Authentication
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="(collapse)" id="collapsePages" aria-labelledby="headingTwo"
                            data-parent="#sidenavAccordion">

                            <nav class="sb-sidenav-menu-nested nav">
                                {% if user.is_authenticated %}
                                <a class="nav-link" href="{% url 'register_app:logout'%}"><i class="fas fa-sign-out-alt"></i>Logout</a>
                                <a class="nav-link" href="/reset_password"><i class="fas fa-bars"></i><span class="ml-1"></span>Change Password</a>

                                {% else %}

                              


                               
                                    <a class="nav-link" href="{% url 'register_app:login'%}">Login</a>
                              
                                <a class="nav-link" href="{% url 'register_app:register'%}">Register</a>
                                {% endif %}
                                  
                            </nav>



                        </div>
                      
                    </div>
                </div>
               
            </nav>
        </div>




    </div>
    </div>

</body>




<br><br><br>


{% if request.user.is_authenticated %}

        <div class="text-center"><strong>Time : {{current_date}}</strong></div>
        <!-- <div class="text-center"><strong>Last Login : {{current_date}}</strong></div> -->


{% endif %}
   


<br>
<div class="card" style="margin-left:18%;margin-right:10%;">

    <h3 class="card-header border-dark" style="text-align:center;">Supermarket Management System</h3>
   
</div>
<img src="static/image/supermarket.jpg" />

<style>
    img {
        width: 70%;
        height: 430px;
        margin-top: 1%;
        margin-bottom: 2%;
        margin-left:19%;
    }

    body{
		background: #a1c4fd;
	
	  }
</style>

{% endblock %}

registers/templates/registers/index_search.html
{% load crispy_forms_tags %}

<form class="navbar-form mr-2" role="search"  method="get">
    <div class="input-group cust-input">
      <!-- <input type="text" class="form-control" placeholder="Search" name="search"> -->
      {{myFilter.form|crispy}}  
      
      <div class="input-group-btn ">
        <button type="submit" class="btn btn-primary">Search</button>
 

      </div>
    </div>
  </form>

registers/templates/registers/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}



<div style="margin-left:20%;margin-right:2%;">





</div>
<div id="layoutAuthentication">
  <div id="layoutAuthentication_content">
    <main>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">


              <div class="card-header">
                <h2 class="text-center font-weight-light my-4">Login</h2>
              </div>

              <div class="card-body">

                <form method="POST" class="justify-content-center">
                  {% csrf_token %}

                  {{form|crispy}}



                  <input type="submit" name="submit" value="Login" class="btn btn-block btn-success">
                  <div class="form-check mt-2 mr-sm-2">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      id="inlineFormCheck"
                    />
                    <label class="form-check-label" for="inlineFormCheck">
                      Remember me
                    </label>
                  </div><hr>

                  <div class="row">
                    <div class="col">
                      <a  class="small" href="/reset_password/">Forgot Password?</a>


                    </div>
                    <div class="col">
                    <a class="small" href="{% url 'register_app:register'%}"> Create New Account!</a>
                    </div>
                  </div>
                </form>

              </div>

            </div>
          </div>
        </div>
      </div>
    </main>
  </div>

</div>

<style>
  body{
		background: #a1c4fd;
	
	  }
</style>


{% endblock %}

registers/templates/registers/logout.html
{% extends 'base.html'%}

{% block content %}


<body>
    <h1>Logout Success</h1>
    <a href="{% url 'register_app:login'%}">Login in again</a>
</body>

{% endblock %}

registers/templates/registers/navbar.html
{% load static %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard</title>
    <!--I include this later-->
    <link href="{% static 'vendor/css/styles.css' %}" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
        crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"
        crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Supermarket</a><button class="btn btn-link btn-sm order-1 order-lg-0"
            id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i></button><!-- Navbar Search-->

            
            <!--form search-->
         
        <form method="GET" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-4 my-2 my-md-0" >
                <div class="input-group">
                <!-- <input class="form-control" type="text" placeholder="Search for..." aria-label="Search"
                    aria-describedby="basic-addon2" /> -->
                
                    {{myFilter.form.name}}
                
                <div class="input-group-append">
                    <button class="btn btn-success" type="button">
                        Search
                        <!-- <i class="fas fa-search"></i> -->
                    </button>
                </div>
            </div> 
        </form>
    
       
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'register_app:login'%}">Logout</a>
                </div>
            </li>
        </ul>
    </nav>

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Functions</div>
                        <a class="nav-link" href="/">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-tachometer-alt"></i>
                            </div>
                            Dashboard
                        </a>
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                            aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-columns"></i>
                            </div>
                            Pages
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>

                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{% url 'product_app:list'%}">Products</a>
                                <a class="nav-link" href="{% url 'order_app:list'%}">Orders</a>
                                <a class="nav-link" href="{% url 'customer_app:list'%}">Customers</a>
                            </nav>
                        </div>

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                            aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-book-open"></i>
                            </div>
                            Authentication
                            <div class="sb-sidenav-collapse-arrow">
                                <i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo"
                            data-parent="#sidenavAccordion">
                            
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="{% url 'register_app:login'%}">Login</a>
                                        <a class="nav-link" href="{% url 'register_app:register'%}">Register</a><a
                                            class="nav-link" href="#">Forgot Password</a>
                                    </nav>
                            

                          
                        </div>
                        <div class="sb-sidenav-menu-heading">Addons</div>
                        <a class="nav-link" href="#">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-chart-area"></i>
                            </div>
                            Charts
                        </a><a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon">
                                <i class="fas fa-table"></i>
                            </div>
                            Tables
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Admin
                </div>
            </nav>
        </div>
    
       
            
         
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
    <script src="js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/chart-area-demo.js"></script>
    <script src="assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="assets/demo/datatables-demo.js"></script>
</body>

</html>