registers/urls.py
from django.urls import path

from registers import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetDoneView

app_name ='register_app'

urlpatterns = [
    path('login/',views.loginPage,name="login"),
    path('register/',views.SignupView,name="register"),
    path('logout/',views.UserLogout.as_view(),name="logout"),
    # path('dash/<int:cid>/',views.dashboard_data,name = "dash-price-data")
  
    # path('logout/',a)
   
]



'''
for which email is sent use SMTP configuration in settings.py
https://docs.djangoproject.com/en/3.0/topics/auth/default/
Submit email form    -->PasswordResetViews.as_views()
email sent success  -->PasswordResetDoneView.as_views()
Link to password reser form in email ---user see email   -->PasswordResetConfirmView.as_views()
password sucessfully changed message and user can login using new password   -->PasswordResetCompleteView.as_views()


-------------------------------------------------------------
-->python decouple concept for email and other things secrete|
--------------------------------------------------------------
'''

sales/urls.py
from django.urls import path
from .views import *

urlpatterns=[
path('',sales_list,name='sales-list'),
path('customers/index/',manage_customers,name='customer-list'),
  path('<pk>/update/', CustomerUpdateView.as_view(), name='customer-update'),
path('<pk>/delete/', CustomerDeleteView.as_view(), name='customer-delete'),
path('create-customer/', CustomerAddView.as_view(), name='create-customer'),
path('sale-detail/<int:pk>',sales_details, name='sales_details'),
path('sales-detail/<int:pk>',sales_details_from_report, name='sales_details_from_report'),

path('<int:sales_id>/update/', SalesUpdateView, name='sales-update'),
path('return/',view_customer_return,name='sales-return-list'),
path('return/<pk>/',return_customer_each_sales,name='return-customer-sale'),
path('existing/',existing_customer_list,name='existing-customer-list'),
path('create/<int:pk>',SalesCreateView.as_view(),name='sales-create'),

path('exist/create/<int:pk>',existing_sales_create.as_view(),name='existing-sales-create'),
path('<int:pk>/return/',SalesReturnView.as_view(),name='sales-return'),

path('get-total-stock/',get_total_stock,name='get-total-stock'),
path('sales-item-total-price/',sales_item_total_price,name='sales-item-total-price'),
path('return-product-list/',product_return_list,name='return-product-list'),


]

school_app/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import *
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
urlpatterns = [
  path('dashboard/', dashboard, name='home'),
  path('', front_page, name='front_page'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    	path('authentication/',include('registers.urls', namespace = 'register_app')),
    # path('', include('corecode.urls')),
    # path('student/', include('students.urls')),
    # path('finance/', include('finance.urls')),
    path('inventory/', include('Inventory.urls')),
    path('supplier/', include('supplier.urls')),
    path('sales/', include('sales.urls')),
        path('report/', include('report.urls')),
    
	path('reset_password/',auth_views.PasswordResetView.as_view(template_name = 'passwordreset/password_reset_email.html'), 
		 name = "password_reset"),
	
	path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(template_name = 'passwordreset/password_reset_sent.html'), 
		 name = "password_reset_done"),
	
	path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/password_reset_form.html'),
		 name="password_reset_confirm"),  
	   
	 #<token> check  for valid user or not--><uidb64> user id encoded in base 64--this email is sent to the user
	 #<uidb64> helps to know user who request for password
	path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/password_reset_complete.html'),
		 name="password_reset_complete"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load auth_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>{{ school_name | default:"Grocery Inventory" }}</title>
<!--  <link href="{% static 'dist/css/style.css' %}" rel="stylesheet" />-->

  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet"
    href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    {% include "datatables_css.html" %}
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700"
    rel="stylesheet">


</head>

<body
  class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light" >
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i
              class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
          <a href="{% url 'home' %} " class="nav-link"><i class="fa fa-home"></i></a>
        </li>
      </ul>



      <!-- Right navbar links -->
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        
        <span class = "mt-2 text-bold">     Welcome,   {{request.user.username}}</span>
        {% else %}
        <span class = "mt-2 text-bold">     Welcome,   anonymous </span>
        {% endif %}

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-user"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <a href="#" class="dropdown-item">
              <i class="fas fa-user mr-2"></i> Profile
            </a>
            <div class="dropdown-divider"></div>
            {% if request.user.is_authenticated %}
            <a href="{% url 'register_app:logout' %}" class="dropdown-item">
              <i class="fas fa-sign-out"></i> Sign out
            </a>
            {% else %}
            <a href="{% url 'register_app:login' %}" class="dropdown-item">
              <i class="fas fa-sign-out"></i> Login
            </a>
            {% endif %}
           
         


          </div>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4" style="background:#1f12d3;border-radius:12px;">
      <!-- Brand Logo -->
      <a href="{% url 'home' %}"  class="brand-link" style="background:#1f12d3;border-radius:12px;">{{ school_name | default:"Grocery Inventory" }}</a>

      <!-- Sidebar -->
      <div class="sidebar">

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column"
            data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-header">Inventory</li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'home' %}" class="nav-link">
                <i class="nav-icon fas  fa-tachometer-alt"></i>
                <p>
              Dashboard
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'inventory_list' %}" class="nav-link">
                <i class="nav-icon fas fa-graduation-cap"></i>
                <p>
                 Manage Products
                </p>
              </a>
            </li>


                        <li class="nav-item">
              <a href="{% url 'supplier-list' %}" class="nav-link">
                <i class="nav-icon fas fa-money-bill-alt"></i>
                <p>
                 Manage Supplier
                </p>
              </a>
            </li>

             
            <li class="nav-item">
              <a href="{% url 'create-customer' %}" class="nav-link">
                <i class="nav-icon fas fa-store"></i>
                <p>
                Create   Customer 
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'customer-list' %}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                Manage   Customer 
                </p>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'existing-customer-list' %}" class="nav-link">
                <i class="nav-icon fas fa-users"></i>
                <p>
                  Sales to Customer
                </p>
              </a>
            </li> 
           <!-- <li class="nav-item">
              <a href="{% url 'sales-list' %}" class="nav-link">
                <i class="nav-icon fas fa-store"></i>
                <p>
                  Manage Sales
                </p>
              </a>
            <!-- </li>   -->
            

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas  fa-book"></i>
              <p>
                Manage Return
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
      
            <ul class="nav nav-treeview">
              <li class="nav-item"> 
                <a href="{% url 'sales-return-list' %}" class="nav-link">
                  <i class="nav-icon fas fa-undo"></i>
                  <p>
                    Sales Return
                  </p>
                </a>
              </li> 
            </li> 
              <li class="nav-item">
                <a href="{% url 'return-product-list' %}" class="nav-link">
                  <i class="fas  fa-circle"></i>
                  <p>
                    Return List
          
                  </p>
                </a>
              </li>
             
          
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="fas  fa-book"></i>
              <p>
                Report
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
      
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'product_report' %}" class="nav-link">
                  <i class="fas  fa-circle"></i>
                  <p>
                    Product
          
                  </p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'customers_report' %}" class="nav-link">
                  <i class="fas  fa-circle"></i>
                  <p>
                    Sales
          
                  </p>
                </a>
              </li>
             
          
            </ul>
          </li>
                  <li class="nav-item">
          <a href="{% url 'register_app:logout' %}" class="nav-link">
            <i class="nav-icon fas fa-sign-out-alt"></i>
            <p>
              Logout
            </p>
          </a>
        </li>
           

            {% else %}
            <li class="nav-item">
              <a href="{% url 'register_app:login' %}" class="nav-link">
                <i class="nav-icon fas fa-sign-in-alt"></i>
                <p>
                  Login
                </p>
              </a>
            </li>
            {% endif %}

          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <section class="content-header">
        <div class="container-fluid">
          <div class="row mb-1">
            <div class="col-sm-8">
              <h1>{% block title %}{% endblock title %}</h1>
            </div>
            <div class="col-sm-4">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">{% block breadcrumb %}{% endblock breadcrumb %}</li>
              </ol>
            </div>
          </div>
        </div><!-- /.container-fluid -->
      </section>
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              {% block fullcard %}
              <div class="card">
                {% block content-header %}{% endblock content-header %}
                <div class="card-body">
                  <div class="row">
                    <div class="col">
                      {% block content %}

                      {% endblock content %}
                    </div>
                  </div>
                  <!-- /.row -->
                </div>
                <!-- ./card-body -->

              </div>
              {% endblock fullcard %}
              <!-- /.card -->
            </div>
            <!-- /.col -->
          </div>
          <!-- /.row -->
        </div>
        <!--/. container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->


  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  

  <!-- jQuery -->
  <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!--  <script src="{% static 'dist/js/jquery.formset.js' %}"> </script>-->
  <!-- Bootstrap -->
  <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
  <!-- overlayScrollbars -->
  <script
    src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>

    
  <!-- AdminLTE App -->
  <script src="{% static 'dist/js/adminlte.js' %}"></script>

  <!-- OPTIONAL SCRIPTS -->
  <script src="{% static 'dist/js/demo.js' %}"></script>

  {% if messages %}
  {% for message in messages %}
  <script type=text/javascript>
    toastr.options.progressBar = true;
    toastr.{{ message.tags }}('{{ message }}')
  </script>
  {% endfor %}
  {% endif %}
  {% include "datatables_js.html" %}


  <script>
    (function ($) {
      $('.clickable-row').css('cursor', 'pointer');
      $(".clickable-row").click(function () {
        window.location = $(this).data("href");
      });
    })(jQuery)

  </script>

  {% block morejs %}

  {% endblock morejs %}

  {% block javascript %}

  {% endblock javascript %}

</body>

</html>

templates/datatables_css.html
{% load static %}
{% comment %} <link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/material-components-web/4.0.0/material-components-web.min.css"
/>
<link
rel="stylesheet"
href="https://cdn.datatables.net/1.11.5/css/dataTables.material.min.css"
/> {% endcomment %}
<link
rel="stylesheet"
href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'plugins/datatables-select/css/select.bootstrap4.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'plugins/datatables-fixedheader/css/fixedHeader.bootstrap4.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'plugins/datatables-rowreorder/css/rowReorder.bootstrap4.min.css' %}"
/>
<link
rel="stylesheet"
href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.css' %}"
/>

templates/datatables_js.html
{% load static %}
<script src="{% static 'plugins/datatables/dataTables.js' %}"></script>
<script src="{% static 'plugins/datatables-select/js/dataTables.select.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-rowreorder/js/rowReorder.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-rowreorder/js/dataTables.rowReorder.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.flash.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.js' %}"></script>
<script src="{% static 'plugins/select2/js/select2.min.js' %}"></script>
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>



<script>
  $(function () {
    $('#dataTable').DataTable({
        dom: 'lBrftip',
        responsive: true,
        
        buttons: {
            buttons: [

         
            { extend: 'print', className: 'btn-datatables' },
            { extend: 'csv', className: 'btn-datatables' },
            { extend: 'excel', className: 'btn-datatables' },
             
                { extend: 'copy', className: 'btn-datatables'},
        
            ],
        },
       
    });
});

$(document).ready(function() {
   // $('select').select2({theme:"bootstrap4"});
});
  </script>

templates/front_page.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}


{% endblock breadcrumb %}

{% block content %}
<img src="{% static 'images/home_page.jpg' %}" alt="" style="width:100%;height:50%;" class="img-circle" />
 
{% endblock content %}



{% block morejs %}


{% endblock morejs %}

templates/index.html
{% extends 'base.html' %}


{% block title %}Dashboard{% endblock title %}

{% block content %}
    <!-- Widgets  -->
    <div class="row">
        <div class="col-lg-3 col-md-6">

            <div class="card">
                <div class="card-body text-white"  style="background-color: #743DB8;">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-1">
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                            <i class="fa fa-cart-plus"></i>
                            Today Incomes<br>
                                <div class="stat-text"><span class="count text-white"><b>Rs.{{ today_sales_price }}</b> </span></div>
<!--                                <div class="stat-heading">Order</div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body bg-info">
                    <div class="stat-widget-five">
                       
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-icon dib flat-color-1">
                                </div>
                                <i class="fa fa-cart-plus"></i>
                                Today Sales
                                <div class="stat-text"><span class="count"><b>{{ order }}</b>   </span></div>
<!--                                <div class="stat-heading">Order</div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body bg-warning">
                    <div class="stat-widget-five">
                       
                        <div class="stat-content">
                            <div class="text-left dib">
                                <div class="stat-icon dib flat-color-2">
                                   
                                </div> 
                                <i class="fab fa-product-hunt"></i> Total Product
                                <div class="stat-text"><span class="count"><b>{{ product }}</b></span></div>
<!--                                <div class="stat-heading">Product</div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body bg-success">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-3">
                          
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <i class="fa fa-paper-plane"></i>  Total Supplier
                                <div class="stat-text"><span class="count"><b> {{supplier}}</b> </span></div>
<!--                                <div class="stat-heading">Supplier</div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-3 col-md-6">
            <div class="card">
                <div class="card-body bg-primary">
                    <div class="stat-widget-five">
                        <div class="stat-icon dib flat-color-4">
                      
                        </div>
                        <div class="stat-content">
                            <div class="text-left dib">
                                <i class="fa fa-users"></i>   Today Buyer
                                <div class="stat-text"><span class="count"><b>{{ customer }}</b>   </span></div>
<!--                                <div class="stat-heading">Buyer</div>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        
      
    </div>

    <!-- /Widgets -->

    <div class="clearfix"></div>
    
    <!-- Orders -->
    <div class="orders">
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        <h4 class="box-title">Orders Summary </h4>
                    </div>
                    <div class="card-body">
                        <div  class="table-stats order-table ov-h">
                            <table id = "dataTable" class="table ">
                                <thead>
                                    <tr>
                                        <th class="serial">#</th>
                                        <th>Supplier</th>
                                        <th>Product</th>
                                        <th>Buyer</th>
                                        <th>Date</th>
                                        {% comment %} <th>Status</th> {% endcomment %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if orders %}
                                    {% for order in orders %}
                                    <tr>
                                        <td class="serial">{{ forloop.counter }}</td>
                                        <td>{{ order.product.supplier }}</td>
                                        <td>{{ order.product }}</td>
                                        <td>{{ order.sales_id.customer }}</td>
                                        <td>{{ order.created_at }}</td>
                                        {% comment %} <td>
                                            {% if order.status == 'pending' %}
                                                <a class="btn btn-warning" href="">{{ order.status }}</a>
                                            {% elif order.status == 'decline' %}
                                                <a class="btn btn-danger" href="">{{ order.status }}</a>
                                            {% elif order.status == 'complete' %}
                                                <a class="btn btn-success" href="">{{ order.status }}</a>
                                            {% elif order.status == 'approved' %}
                                                <a class="btn btn-primary" href="">{{ order.status }}</a>
                                            {% elif order.status == 'bulk' %}
                                                <a class="btn btn-secondary" href="">{{ order.status }}</a>
                                            {% else %}
                                                <a class="btn btn-info" href="">{{ order.status }}</a>
                                            {% endif %}
                                        </td> {% endcomment %}
                                    </tr>
                                    {% endfor %}
                                    {% else %}
                                        <tr><td>No Order Data</td></tr>
                                    {% endif %}
                                </tbody>
                            </table>
                        </div> <!-- /.table-stats -->
                    </div>
                </div> <!-- /.card -->
            </div>  <!-- /.col-lg-8 -->


        </div>
    </div> 
    <!-- /.orders -->
{% endblock content %}
{% block javascript %}

{% endblock javascript %}

templates/paginator.html
{% if page_obj.has_other_pages %}
<div aria-label="pagination">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
      </li>
    {% endif %}

    {% for page in page_obj.paginator.page_range %}

      {% if page_obj.number == page %}
        <li class="page-item active" aria-current="page">
          <span class="page-link">{{ page }}<span class="sr-only">(current)</span>
          </span>
        </li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page }}">{{ page }}</a></li>
      {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      </li>
      {% endif %}
  </ul>
</div>

{% endif %}